apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: first-run-database-setup
  labels:
    app: rails
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: rails-app:latest
        name: first-rails-app
        imagePullPolicy: Never
        command: ['bin/rake','db:reset']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_DATABASE_URL
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_SECRET_TOKEN
        ports:
        - containerPort: 9000
          name: rails-port
