apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: rails
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: rails
    tier: database
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgres
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
      tier: database
  template:
    metadata:
      labels:
        app: rails
        tier: database
    spec:
      containers:
      - image: postgres:9.4.5
        name: postgres
        env:
        - name: POSTGRES_USER
          value: drkiq
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: PG_PASSWORD
        ports:
        - containerPort: 5432
          name: pg
        volumeMounts:
        - name: pg-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-persistent-storage
        hostPath:
          path: /data/drkiq-postgres
          type: DirectoryOrCreate
