apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: rails
spec:
  ports:
    - port: 8080
      targetPort: 9000
  selector:
    app: rails
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rails
        tier: backend
    spec:
      containers:
      - image: rails-app
        name: rails
        env:
        - name: LISTEN_ON
          value: 0.0.0.0:9000
        - name: WORKER_PROCESSES
          value: 2
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_DATABASE_URL
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_SECRET_TOKEN
        ports:
        - containerPort: 9000
          name: rails-app-port
        volumeMounts:
        - name: rails-persistent-storage
          mountPath: /drkiq
      volumes:
      - name: rails-persistent-storage
        hostPath:
          path: ./app/drkiq
          type: Directory
