apiVersion: v1
kind: Service
metadata:
  name: rails-app
  labels:
    app: rails
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: rails
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rails-app
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
      tier: backend
  template:
    metadata:
      labels:
        app: rails
        tier: backend
    spec:
      containers:
      - image: rails-app:latest
        name: rails-app
        imagePullPolicy: Never
        env:
        - name: LISTEN_ON
          valueFrom:
            configMapKeyRef:
              name: rails-configmap
              key: LISTEN_ON
        - name: WORKER_PROCESSES
          valueFrom:
            configMapKeyRef:
              name: rails-configmap
              key: WORKER_PROCESSES
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_DATABASE_URL
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: RAILS_SECRET_TOKEN
        ports:
        - containerPort: 9000
          name: rails-port
