apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
type: Opaque
data:
  PG_PASSWORD: ZHJraXE=
  RAILS_SECRET_TOKEN: YjczN2IxZjQ1N2Q3YzQzYmY1ZTQ5MjAxZTYxYmFlNTU0NDBiYTg4OTQyNjFiYWVhYTM1NDgyMmZhNTBhMTdlOTM0MWU3NzQ1Yjc3MjQwNzA1OWE4Y2E5YzViY2RhM2VhMGNiZWQ2YmRhZWMxOGNjMjUzZjM5M2RmYjU1MTY2Yzg=
  RAILS_DATABASE_URL: cG9zdGdyZXNxbDovL2Rya2lxOmRya2lxQHBvc3RncmVzOjU0MzIvZHJraXE/ZW5jb2Rpbmc9dXRmOCZwb29sPTUmdGltZW91dD01MDAw
